window.SKILLS = [
  {
    "skill": "Adobe Acrobat",
    "license": "Free with limited functionality; commercial Pro available",
    "pricing": "Free Reader; Acrobat Pro subscription or perpetual legacy license depending on version",
    "platforms": "Mac, Windows, Web, Android, iPhone, iPad, Chrome OS",
    "complements": "PDF readers, document workflows",
    "details": "Create, edit, combine, sign, compress, OCR, export, and review PDFs.",
    "proof": "Add PDF proof or document packet URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Adobe Animate",
    "license": "Commercial",
    "pricing": "Creative Cloud subscription, often about $21-$83/month depending on plan",
    "platforms": "Mac, Windows",
    "complements": "Authoring environments, animation",
    "details": "2D animation, interactive assets, HTML5 canvas, character and timeline animation.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Adobe Illustrator",
    "license": "Commercial",
    "pricing": "Creative Cloud subscription, often about $21-$83/month depending on plan",
    "platforms": "Mac, Windows, iPad",
    "complements": "Photo editors and graphic file networks",
    "details": "Vector illustration, icons, logos, typography, SVG/PDF/EPS export.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Adobe Lightroom",
    "license": "Commercial",
    "pricing": "Photography/Creative Cloud subscription, often about $10-$83/month depending on plan",
    "platforms": "Mac, Windows, Web, Android, iPhone, iPad",
    "complements": "Mobile photo editors and graphic file networks",
    "details": "Photo organization, RAW editing, color correction, presets, export workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Adobe Photoshop",
    "license": "Commercial",
    "pricing": "Photography/Creative Cloud subscription, often about $10-$83/month depending on plan",
    "platforms": "Mac, Windows, Web, iPad",
    "complements": "Photo editors and graphic file networks",
    "details": "Raster editing, compositing, retouching, masks, layers, generative and export workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Adobe Premiere Pro",
    "license": "Commercial",
    "pricing": "Creative Cloud subscription, often about $21-$83/month depending on plan",
    "platforms": "Mac, Windows",
    "complements": "Video and movies",
    "details": "Timeline editing, color, audio, captions, export presets, social/video delivery.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "After Effects",
    "license": "Commercial",
    "pricing": "Creative Cloud subscription, often about $21-$83/month depending on plan",
    "platforms": "Mac, Windows",
    "complements": "Video and movies",
    "details": "Motion graphics, compositing, keyframes, titles, VFX, animated explainers.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Agile Methodologies",
    "license": "N/A - skill or standard",
    "pricing": "Free to learn; paid courses/certs optional",
    "platforms": "Cross-platform / role-based",
    "complements": "Project management, software delivery",
    "details": "Scrum/Kanban terms, sprints, backlog, estimation, retrospectives, incremental delivery.",
    "proof": "Add work sample, certificate, repo, or case-study URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Amazon Web Services (AWS)",
    "license": "Commercial cloud platform",
    "pricing": "Free tier available; pay-as-you-go for usage",
    "platforms": "Web console, CLI, SDKs; cross-platform",
    "complements": "Cloud hosting, databases, storage, DevOps",
    "details": "EC2, S3, IAM, Lambda, RDS, CloudWatch, deployment and cost awareness.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Android",
    "license": "Open source core plus commercial Google services",
    "pricing": "Free SDK; Play fees and devices optional",
    "platforms": "Android devices, Android Studio on Mac/Windows/Linux",
    "complements": "Mobile app development",
    "details": "Activities, layouts, permissions, Gradle, testing, publishing basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "AngularJS",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Web browsers; Node tooling",
    "complements": "JavaScript frameworks",
    "details": "Legacy AngularJS controllers, directives, services, routing, binding, migration awareness.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "ArcGIS",
    "license": "Commercial with educational/trial options",
    "pricing": "Subscription/licensing varies by Esri plan",
    "platforms": "Windows, Web, Mobile",
    "complements": "GIS, mapping, data visualization",
    "details": "Layers, geodatabases, maps, spatial analysis, dashboards, exports.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "AutoCAD",
    "license": "Commercial",
    "pricing": "Subscription; educational access may be free",
    "platforms": "Windows, Mac, Web, Mobile",
    "complements": "CAD and drafting",
    "details": "2D drafting, dimensions, layers, blocks, model/paper space, DWG/PDF output.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Autodesk Fusion 360",
    "license": "Commercial with free personal/education options",
    "pricing": "Subscription; personal/education options may be free",
    "platforms": "Windows, Mac, Web viewer",
    "complements": "CAD/CAM/CAE and 3D design",
    "details": "Parametric modeling, assemblies, simulation, rendering, CAM basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Autodesk Inventor",
    "license": "Commercial with educational access",
    "pricing": "Subscription; education access may be free",
    "platforms": "Windows",
    "complements": "Mechanical CAD",
    "details": "Parts, assemblies, constraints, drawings, BOMs, mechanical design workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Autodesk Maya",
    "license": "Commercial with educational access",
    "pricing": "Subscription; education access may be free",
    "platforms": "Windows, Mac, Linux",
    "complements": "3D animation and modeling",
    "details": "Modeling, rigging, animation, lighting, rendering, asset export.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Avid Media Composer",
    "license": "Commercial",
    "pricing": "Subscription/perpetual options vary by plan",
    "platforms": "Windows, Mac",
    "complements": "Professional video editing",
    "details": "Timeline editing, bins, media management, multicam, color and audio handoff.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Bash",
    "license": "Open source shell",
    "pricing": "Free",
    "platforms": "Linux, macOS, Windows via WSL/Git Bash",
    "complements": "Command line, automation",
    "details": "Shell scripting, pipes, files, permissions, process automation.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "C",
    "license": "Language standard",
    "pricing": "Free compilers available",
    "platforms": "Cross-platform",
    "complements": "Systems programming",
    "details": "Pointers, memory, compilation, data structures, debugging fundamentals.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "CSS",
    "license": "Open web standard",
    "pricing": "Free",
    "platforms": "Web browsers",
    "complements": "HTML and frontend UI",
    "details": "Selectors, layout, Flexbox/Grid, responsive design, typography, animations.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Django",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Cross-platform Python web stack",
    "complements": "Python web frameworks",
    "details": "Models, views, templates, admin, auth, ORM, deployment basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Dreamweaver",
    "license": "Commercial",
    "pricing": "Creative Cloud subscription",
    "platforms": "Mac, Windows",
    "complements": "Web authoring environments",
    "details": "Visual and code-based web editing, site management, HTML/CSS workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Eclipse",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Windows, Mac, Linux",
    "complements": "Java IDEs",
    "details": "Java projects, debugging, build tools, plugins, workspace management.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Final Cut Pro",
    "license": "Commercial",
    "pricing": "One-time purchase from Apple",
    "platforms": "Mac, iPad",
    "complements": "Video and movies",
    "details": "Magnetic timeline, multicam, color, titles, audio, Apple media workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Git",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Windows, Mac, Linux",
    "complements": "Version control",
    "details": "Commits, branches, merges, remotes, GitHub/GitLab workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Google Analytics",
    "license": "Free/commercial tiers",
    "pricing": "GA4 free tier; enterprise pricing for Analytics 360",
    "platforms": "Web",
    "complements": "Marketing analytics",
    "details": "Events, conversions, reports, traffic sources, campaign measurement.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Google Cloud Platform (GCP)",
    "license": "Commercial cloud platform",
    "pricing": "Free tier/trial available; pay-as-you-go",
    "platforms": "Web console, CLI, SDKs; cross-platform",
    "complements": "Cloud hosting, data, AI, DevOps",
    "details": "Compute, storage, IAM, Cloud Run, BigQuery, monitoring basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "HTML",
    "license": "Open web standard",
    "pricing": "Free",
    "platforms": "Web browsers",
    "complements": "Web development",
    "details": "Semantic markup, forms, media, accessibility, document structure.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Hadoop",
    "license": "Open source ecosystem",
    "pricing": "Free software; hosting/support may cost",
    "platforms": "Linux, cloud platforms",
    "complements": "Big data processing",
    "details": "HDFS, MapReduce, YARN, distributed data concepts.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "InDesign",
    "license": "Commercial",
    "pricing": "Creative Cloud subscription",
    "platforms": "Mac, Windows",
    "complements": "Page layout and publishing",
    "details": "Layouts, styles, master pages, typography, PDF export, print/digital publishing.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "jQuery",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Web browsers",
    "complements": "JavaScript libraries",
    "details": "DOM selection, events, Ajax, effects, legacy web maintenance.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "JSON",
    "license": "Open data format",
    "pricing": "Free",
    "platforms": "Cross-platform",
    "complements": "APIs and data exchange",
    "details": "Objects, arrays, validation, API payloads, configuration files.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Java",
    "license": "Open source/commercial distributions",
    "pricing": "Free OpenJDK; commercial support optional",
    "platforms": "Windows, Mac, Linux, servers",
    "complements": "Backend and enterprise development",
    "details": "OOP, collections, exceptions, streams, JVM, build tools.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Advanced Java Compiler",
    "license": "Project/tool entry",
    "pricing": "Free if based on open compiler stack; hosting may cost",
    "platforms": "Web or desktop depending on implementation",
    "complements": "Java, Spring, Maven",
    "details": "Compile/run workflows, diagnostics, classpath, syntax/runtime feedback.",
    "proof": "Add compiler demo URL or GitHub repo",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "JavaScript",
    "license": "Open web standard",
    "pricing": "Free",
    "platforms": "Web browsers, Node.js",
    "complements": "Frontend and backend development",
    "details": "DOM, async code, fetch, modules, events, testing basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Keynote",
    "license": "Commercial/free Apple app",
    "pricing": "Free with Apple devices",
    "platforms": "Mac, iPhone, iPad, Web via iCloud",
    "complements": "Presentations",
    "details": "Slide design, builds, media, exports, speaker notes.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Kotlin",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "JVM, Android, native/multiplatform",
    "complements": "Android and backend development",
    "details": "Null safety, classes, coroutines, Android patterns.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Logic Pro",
    "license": "Commercial",
    "pricing": "One-time purchase from Apple",
    "platforms": "Mac, iPad",
    "complements": "Audio production",
    "details": "Recording, MIDI, mixing, plugins, arrangement, export workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "MATLAB",
    "license": "Commercial",
    "pricing": "License/subscription varies; student options available",
    "platforms": "Windows, Mac, Linux, Web",
    "complements": "Engineering, math, data analysis",
    "details": "Matrices, plotting, scripts, toolboxes, simulations.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Maven",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Cross-platform Java tooling",
    "complements": "Java build systems",
    "details": "POM files, dependencies, lifecycle, packaging, repositories.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft Access",
    "license": "Commercial",
    "pricing": "Microsoft 365 or standalone license depending on plan",
    "platforms": "Windows",
    "complements": "Databases and office workflows",
    "details": "Tables, forms, queries, reports, small business databases.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft Excel",
    "license": "Commercial",
    "pricing": "Microsoft 365 subscription or standalone license",
    "platforms": "Windows, Mac, Web, Mobile",
    "complements": "Spreadsheets and data analysis",
    "details": "Formulas, pivot tables, charts, cleaning, dashboards, imports/exports.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft Outlook",
    "license": "Commercial/free tiers",
    "pricing": "Microsoft 365 subscription; free Outlook web/mail tiers available",
    "platforms": "Windows, Mac, Web, iOS, Android",
    "complements": "Email and calendar",
    "details": "Email management, calendar, rules, contacts, meeting coordination.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft Power BI",
    "license": "Commercial/free desktop",
    "pricing": "Free Desktop; Pro/Premium subscriptions for sharing",
    "platforms": "Windows, Web, Mobile",
    "complements": "Business intelligence",
    "details": "Data models, DAX, visuals, dashboards, refresh, publishing.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft PowerPoint",
    "license": "Commercial",
    "pricing": "Microsoft 365 subscription or standalone license",
    "platforms": "Windows, Mac, Web, Mobile",
    "complements": "Presentations",
    "details": "Slide design, templates, charts, media, presenter workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft Project",
    "license": "Commercial",
    "pricing": "Subscription/license varies by plan",
    "platforms": "Windows, Web",
    "complements": "Project management",
    "details": "Schedules, dependencies, Gantt charts, resources, milestones.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft SharePoint",
    "license": "Commercial",
    "pricing": "Microsoft 365 business/enterprise plans",
    "platforms": "Web, Microsoft 365 ecosystem",
    "complements": "Collaboration and document management",
    "details": "Sites, document libraries, permissions, lists, workflow basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft T-SQL",
    "license": "Commercial/open tooling around SQL Server",
    "pricing": "SQL Server Developer free; production licensing varies",
    "platforms": "Windows, Linux, Azure",
    "complements": "Relational databases",
    "details": "Queries, joins, stored procedures, indexes, SQL Server concepts.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft Visio",
    "license": "Commercial",
    "pricing": "Subscription or standalone license",
    "platforms": "Windows, Web",
    "complements": "Diagrams and process maps",
    "details": "Flowcharts, network diagrams, UML, process documentation.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Microsoft Word",
    "license": "Commercial",
    "pricing": "Microsoft 365 subscription or standalone license",
    "platforms": "Windows, Mac, Web, Mobile",
    "complements": "Documents",
    "details": "Formatting, styles, tables, references, review, PDF export.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "MongoDB",
    "license": "Source-available/community plus commercial Atlas",
    "pricing": "Community free; Atlas free tier and paid usage",
    "platforms": "Windows, Mac, Linux, Cloud",
    "complements": "NoSQL databases",
    "details": "Documents, collections, queries, indexes, aggregation, drivers.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "MySQL",
    "license": "Open source/community plus commercial editions",
    "pricing": "Community free; commercial support/cloud may cost",
    "platforms": "Windows, Mac, Linux, Cloud",
    "complements": "Relational databases",
    "details": "Schemas, queries, joins, indexes, users, backups.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "NoSQL",
    "license": "Database category",
    "pricing": "Depends on product; many free/open options",
    "platforms": "Cross-platform/cloud",
    "complements": "Databases and data architecture",
    "details": "Document/key-value/graph concepts, schema design, scaling tradeoffs.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Node.js",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Windows, Mac, Linux, servers",
    "complements": "JavaScript backend",
    "details": "npm, modules, APIs, Express-style servers, async I/O.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Object-Oriented Programming",
    "license": "N/A - skill or standard",
    "pricing": "Free to learn; paid courses/certs optional",
    "platforms": "Cross-platform / role-based",
    "complements": "Software design",
    "details": "Classes, objects, inheritance, encapsulation, polymorphism, interfaces, SOLID basics.",
    "proof": "Add work sample, certificate, repo, or case-study URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Objective-C",
    "license": "Language/runtime",
    "pricing": "Free tooling via Xcode; Apple hardware may be needed",
    "platforms": "Mac, iOS ecosystem",
    "complements": "Apple development",
    "details": "Classes, messages, memory model, Cocoa/Cocoa Touch basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "PHP",
    "license": "Open source",
    "pricing": "Free; hosting may cost",
    "platforms": "Web servers, Windows, Mac, Linux",
    "complements": "Web backends",
    "details": "Forms, sessions, databases, routing, templates, deployment.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Mini Twitter in PHP",
    "license": "Project entry",
    "pricing": "Free/open stack if self-built; hosting may cost",
    "platforms": "Web",
    "complements": "PHP apps, databases",
    "details": "User posts, timelines, auth, CRUD, database-backed web app.",
    "proof": "Add Mini Twitter repo/demo URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "PHP based app",
    "license": "Project entry",
    "pricing": "Free/open stack if self-built; hosting may cost",
    "platforms": "Web",
    "complements": "PHP apps",
    "details": "Reusable PHP app proof: CRUD, forms, database, deployment, documentation.",
    "proof": "Add PHP app repo/demo URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Pro Tools",
    "license": "Commercial",
    "pricing": "Subscription/perpetual options vary by plan",
    "platforms": "Windows, Mac",
    "complements": "Audio engineering",
    "details": "Recording, editing, mixing, routing, plugins, session delivery.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Python",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Windows, Mac, Linux, Web/cloud",
    "complements": "Automation, data, web, AI",
    "details": "Scripts, packages, virtual environments, APIs, data handling, testing.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "QuickBooks",
    "license": "Commercial",
    "pricing": "Subscription varies by plan",
    "platforms": "Web, Windows, Mac/mobile depending on product",
    "complements": "Accounting and bookkeeping",
    "details": "Invoices, expenses, reports, reconciliations, small business workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "R Programming",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Windows, Mac, Linux, RStudio/Posit",
    "complements": "Statistics and data analysis",
    "details": "Data frames, visualization, statistical analysis, reports.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Cloud, Data & Analytics",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "REST API",
    "license": "Architecture style",
    "pricing": "Free concept; tooling varies",
    "platforms": "Web/cloud",
    "complements": "Web services",
    "details": "HTTP methods, status codes, JSON payloads, auth, API testing.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "React.js",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "Web browsers, Node tooling",
    "complements": "Frontend development",
    "details": "Components, props, state, hooks, routing, API-driven UI.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Revit",
    "license": "Commercial",
    "pricing": "Subscription; educational access may be free",
    "platforms": "Windows",
    "complements": "BIM and architecture",
    "details": "Models, families, sheets, schedules, BIM coordination.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Rhino 3D",
    "license": "Commercial",
    "pricing": "One-time license/upgrade model varies",
    "platforms": "Windows, Mac",
    "complements": "3D modeling",
    "details": "NURBS modeling, surfaces, rendering, fabrication workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Ruby on Rails",
    "license": "Open source",
    "pricing": "Free; hosting may cost",
    "platforms": "Cross-platform Ruby web stack",
    "complements": "Web frameworks",
    "details": "MVC, routes, Active Record, migrations, CRUD apps.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "SOLIDWORKS",
    "license": "Commercial",
    "pricing": "License/subscription varies; student options available",
    "platforms": "Windows",
    "complements": "Mechanical CAD",
    "details": "Parts, assemblies, drawings, simulation, manufacturing handoff.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Scala",
    "license": "Open source",
    "pricing": "Free",
    "platforms": "JVM, Windows/Mac/Linux",
    "complements": "Backend/data engineering",
    "details": "Functional/OOP programming, collections, JVM tooling, Spark awareness.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "SketchUp",
    "license": "Commercial/free web tier",
    "pricing": "Free web tier; Pro subscription for advanced use",
    "platforms": "Web, Windows, Mac, iPad",
    "complements": "3D modeling",
    "details": "Concept modeling, scenes, components, exports, architectural visualization.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Spring Framework",
    "license": "Open source",
    "pricing": "Free; hosting/support optional",
    "platforms": "Java/JVM, servers, cloud",
    "complements": "Java backend",
    "details": "Dependency injection, MVC, Boot, REST services, data access.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Java Spring Boot Compiler",
    "license": "Project/tool entry",
    "pricing": "Free/open stack if self-built; hosting may cost",
    "platforms": "Web or server",
    "complements": "Java, Spring Boot, Maven",
    "details": "Compile/run Spring Boot examples, REST endpoints, diagnostics.",
    "proof": "Add Spring Boot compiler demo/repo URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Spring Boot for Java compiler on the web",
    "license": "Project/tool entry",
    "pricing": "Free/open stack if self-built; hosting may cost",
    "platforms": "Web",
    "complements": "Java, Spring Framework",
    "details": "Browser-based Spring Boot compile/run proof and documentation.",
    "proof": "Add web compiler URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Swift",
    "license": "Open source language with Apple tooling",
    "pricing": "Free Xcode; Apple Developer Program optional",
    "platforms": "Mac, iOS, server/Linux",
    "complements": "Apple app development",
    "details": "Swift syntax, optionals, structs/classes, SwiftUI/UIKit basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Unity",
    "license": "Commercial/free personal tiers",
    "pricing": "Free Personal; paid plans depending on revenue/use",
    "platforms": "Windows, Mac, Linux, iOS, Android, WebGL, consoles",
    "complements": "Game development and 3D",
    "details": "Scenes, assets, C# scripts, physics, UI, builds.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "CAD, 3D & Engineering",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Visual Basic for Applications (VBA)",
    "license": "Microsoft Office scripting",
    "pricing": "Included with supported Office desktop apps",
    "platforms": "Windows, Mac limited by Office app",
    "complements": "Office automation",
    "details": "Macros, forms, Excel automation, Outlook/Access workflows.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Windows Server",
    "license": "Commercial",
    "pricing": "License varies by edition/CALs/cloud provider",
    "platforms": "Windows Server, Azure/cloud",
    "complements": "Server administration",
    "details": "Roles/features, users, file services, IIS, networking, updates.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Business & Productivity",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "WordPress",
    "license": "Open source CMS; hosted services vary",
    "pricing": "Software free; hosting/themes/plugins may cost",
    "platforms": "Web",
    "complements": "Websites and CMS",
    "details": "Pages, posts, themes, plugins, media, SEO basics.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "XML",
    "license": "Open data markup standard",
    "pricing": "Free",
    "platforms": "Cross-platform",
    "complements": "Data exchange and configuration",
    "details": "Tags, attributes, schemas, parsing, config/data files.",
    "proof": "Add portfolio/GitHub/demo/media URL",
    "category": "Software Development",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "iMovie",
    "license": "Free Apple app",
    "pricing": "Free with Apple devices",
    "platforms": "Mac, iPhone, iPad",
    "complements": "Video editing",
    "details": "Simple timeline editing, cuts, transitions, titles, exports. Note: used in various projects; pseudonym reference belongs only here.",
    "proof": "Add iMovie project sample URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  },
  {
    "skill": "Audio Engineering Essentials",
    "license": "N/A - skill or standard",
    "pricing": "Free to learn; paid courses/certs optional",
    "platforms": "Mac, Windows, studio/live environments",
    "complements": "Audio production",
    "details": "Recording, signal flow, editing, EQ, compression, mixing, mastering basics, delivery formats.",
    "proof": "Add audio sample or session screenshot URL",
    "category": "Creative Media",
    "proofUrl": "",
    "status": "Needs proof URL"
  }
];
